// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL0AclZcT8R_hv4u6lUDKAwNiIwiHKxRs',
    appId: '1:351967789232:web:43bba6b496effced4afb75',
    messagingSenderId: '351967789232',
    projectId: 'divelog2-ea9a6',
    authDomain: 'divelog2-ea9a6.firebaseapp.com',
    storageBucket: 'divelog2-ea9a6.firebasestorage.app',
    measurementId: 'G-K39SC9JKT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtEnTk1zeiSnRSOr9wRi8xNeN0850mGLY',
    appId: '1:351967789232:android:861df84b44f66eaa4afb75',
    messagingSenderId: '351967789232',
    projectId: 'divelog2-ea9a6',
    storageBucket: 'divelog2-ea9a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuCKEIMM2e8iXi1LaxZDxs_iDxRICHKgA',
    appId: '1:351967789232:ios:1af3fda90846d7cc4afb75',
    messagingSenderId: '351967789232',
    projectId: 'divelog2-ea9a6',
    storageBucket: 'divelog2-ea9a6.firebasestorage.app',
    iosBundleId: 'com.example.divelog2',
  );
}
